# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
name: "Joystick Java CI/CD Build"
on:
  push:
    branches-ignore:
      - feature/initial_client_impl
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 1.8
        # check available versions https://github.com/actions/setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          cache: 'maven'

      - name: Build with Maven
        run: mvn
